import "server-only"

import { cookies } from "next/headers"

export type ServerLang = "ptBr" | "ptPt" | "en" | "es" | "fr"
type CommonCopy = Record<
  | "logout"
  | "program"
  | "backToBio"
  | "status"
  | "pendingApproval"
  | "approved"
  | "rejected"
  | "suspended"
  | "pending"
  | "available"
  | "paid"
  | "canceled"
  | "code"
  | "viewAll"
  | "admin"
  | "active"
  | "inactive"
  | "moveUp"
  | "moveDown"
  | "edit"
  | "delete"
  | "cancel"
  | "confirmDelete"
  | "close",
  string
>

const copy = {
  ptBr: {
    common: {
      logout: "Sair",
      program: "Programa",
      backToBio: "Voltar para bio",
      status: "Status",
      pendingApproval: "Aguardando aprovação",
      approved: "Aprovado",
      rejected: "Reprovado",
      suspended: "Suspenso",
      pending: "Pendente",
      available: "Disponível",
      paid: "Pago",
      canceled: "Cancelado",
      code: "Código",
      viewAll: "Ver todos",
      admin: "Admin",
      active: "Ativo",
      inactive: "Inativo",
      moveUp: "Subir",
      moveDown: "Descer",
      edit: "Alterar",
      delete: "Excluir",
      cancel: "Cancelar",
      confirmDelete: "Confirmar exclusão",
      close: "Fechar",
    },
    adminHome: {
      eyebrow: "Painel administrativo",
      hello: "Olá,",
      description: "Revise cadastros, acompanhe campanhas e mantenha o programa de influenciadores organizado.",
      statsInfluencers: "Influenciadores",
      statsWaiting: "Aguardando",
      statsApproved: "Aprovados",
      statsRejected: "Reprovados",
      reviewRegistrations: "Aprovar cadastros",
      reviewRegistrationsText: "Revisar solicitações, aprovar, reprovar ou suspender perfis.",
      manageCampaigns: "Gerenciar campanhas",
      campaignsCount: (count: number) => `${count} campanhas disponíveis no programa.`,
      earnings: "Ganhos lançados",
      homeLinks: "Links da página inicial",
      homeLinksCount: (count: number) => `${count} atalhos ativos na home.`,
      documents: "Documentos e materiais",
      documentsCount: (count: number) => `${count} itens cadastrados para influenciadores.`,
      latestRegistrations: "Últimos cadastros",
      influencersToReview: "Influenciadores para revisar",
      emptyLatestRegistrations: "Nenhum cadastro para revisar no momento.",
    },
    account: {
      eyebrow: "Minha conta",
      dashboardEyebrow: "Painel FindB Europa",
      hello: "Olá,",
      description: "Seu link exclusivo, campanhas, materiais, ganhos e estatísticas em uma área simples para compartilhar.",
      accountDescription: "Acesse seu link, status de aprovação, campanhas e materiais.",
      myLink: "Meu link",
      exclusiveUrl: "URL exclusiva",
      shareUrl: "Compartilhe sua URL exclusiva",
      shareHint: "Use esse link em stories, grupos e publicações para registrar seus resultados.",
      clicks: "Cliques",
      registrations: "Cadastros",
      shares: "Compartilhamentos",
      campaigns: "Campanhas",
      contentHub: "Central de conteúdo",
      statement: "Extrato",
      rankingChallenges: "Ranking e desafios",
      noEarnings: "Seus ganhos aparecem aqui quando campanhas forem validadas pela equipe.",
      weeklyRanking: "Ranking semanal",
      monthlyRanking: "Ranking mensal",
      specialMissions: "Missões especiais",
      referralBonus: "Bônus por indicação",
    },
    influencerLogin: {
      eyebrow: "Área do influenciador",
      title: "Minha conta",
      description: "Acesse seu link, status de aprovação, campanhas e materiais.",
    },
    adminLinks: {
      newLink: "Novo link",
      eyebrow: "Página inicial",
      titleStart: "Links",
      titleAccent: "em destaque",
      description: "Cadastre, altere, exclua e organize a ordem dos cards exibidos na página inicial.",
      registered: "Links cadastrados",
      activeHome: "Ativos na home",
      empty: "Nenhum link cadastrado.",
      deleteTitle: "Excluir link",
      deleteDescription: "Essa ação remove o card da página inicial e do painel administrativo.",
    },
    adminLists: {
      newEarning: "Novo ganho",
      earningsBack: "Ganhos",
      earningsEyebrow: "Ganhos lançados",
      earningsTitleStart: "Extrato de",
      earningsTitleAccent: "ganhos",
      earningsDescription: "Consulte os lançamentos feitos para influenciadores, campanhas vinculadas e status de pagamento.",
      launchEarningTitleStart: "Lançar",
      launchEarningTitleAccent: "ganho",
      newEarningDescription: "Registre um valor para um influenciador sem misturar criação com a listagem do extrato.",
      earningFormTitle: "Lançar ganho",
      earningFormDescription: "Valores pendentes ou disponíveis atualizam o saldo do influenciador.",
      influencer: "Influenciador",
      select: "Selecione",
      campaign: "Campanha",
      amountEuros: "Valor em euros",
      earningExample: "Ex: Bônus da campanha de stories",
      savingEarning: "Lançando...",
      noCampaign: "Sem campanha",
      noEarnings: "Nenhum ganho lançado.",
      deleteEarningTitle: "Excluir ganho",
      deleteEarningDescription: "Essa ação remove o lançamento e ajusta o saldo pendente ou disponível do influenciador quando necessário.",
      newCampaign: "Nova campanha",
      campaignsBack: "Campanhas",
      campaignsEyebrow: "Campanhas",
      campaignsTitleStart: "Gerenciar",
      campaignsTitleAccent: "campanhas ativas",
      campaignsDescription: "Cadastre, altere datas, encerre ou exclua campanhas exibidas para influenciadores.",
      createCampaignTitleStart: "Cadastrar",
      createCampaignTitleAccent: "campanha",
      editCampaignEyebrow: "Alterar campanha",
      editCampaignTitleStart: "Editar",
      campaignFormTitle: "Dados da campanha",
      campaignFormDescription: "Campanhas ativas aparecem para influenciadores e na área pública do programa.",
      title: "Título",
      descriptionLabel: "Descrição",
      activeCampaigns: "Ativas",
      pausedDraft: "Pausadas/rascunho",
      endedCampaigns: "Encerradas",
      campaignActive: "Ativa",
      campaignPaused: "Pausada",
      campaignEnded: "Encerrada",
      campaignDraft: "Rascunho",
      objective: "Objetivo",
      material: "Material",
      rewardEuros: "Recompensa em euros",
      materialType: "Tipo de material",
      eventMaterial: "Evento",
      statusField: "Status",
      start: "Início",
      end: "Fim",
      startDate: "Data de início",
      endDate: "Data de fim",
      endDateHelper: "Deixe vazio para campanha sem fim definido.",
      saving: "Salvando...",
      createCampaignSubmit: "Cadastrar campanha",
      saveChanges: "Salvar alterações",
      noEndDate: "Sem data de fim",
      linkedEarnings: (count: number) => `${count} lançamentos de ganhos vinculados.`,
      noCampaigns: "Nenhuma campanha cadastrada.",
      deleteCampaignTitle: "Excluir campanha",
      deleteCampaignDescription: "Essa ação remove a campanha do admin e da área dos influenciadores. Os ganhos vinculados continuam guardados, mas sem campanha associada.",
      newDocument: "Novo documento",
      documentsBack: "Documentos",
      newMaterial: "Novo material",
      editMaterial: "Editar material",
      documentsEyebrow: "Materiais",
      documentsTitleStart: "Documentos",
      documentsTitleAccent: "do programa",
      documentsDescription: "Cadastre regulamentos, materiais para download e links para envio de conteúdo.",
      createDocumentTitleStart: "Cadastrar",
      createDocumentTitleAccent: "documento",
      editDocumentTitleStart: "Alterar",
      editDocumentTitleAccent: "documento",
      documentFormTitle: "Dados do documento",
      documentFormDescription: "Cadastre links para regulamento, materiais de divulgação ou envio de conteúdo.",
      regulations: "Regulamentos",
      materials: "Materiais",
      submissions: "Envios",
      documentRegulation: "Regulamento",
      documentMaterial: "Material",
      documentMaterialDownload: "Material para baixar",
      documentSubmission: "Envio de conteúdo",
      documentStory: "Stories",
      documentScript: "Roteiro",
      documentBrand: "Marca / logotipos",
      documentOther: "Outro documento",
      documentFallback: "Documento",
      type: "Tipo",
      documentUrl: "URL do documento",
      documentUrlHelper: "Use um link interno, PDF, Google Drive, formulário ou arquivo publicado.",
      createDocumentSubmit: "Cadastrar documento",
      open: "Abrir",
      noDocuments: "Nenhum documento cadastrado.",
      deleteDocumentTitle: "Excluir documento",
      deleteDocumentDescription: "Essa ação remove o documento da área de influenciadores e do painel administrativo.",
      moderation: "Moderação",
      influencerApprovalStart: "Aprovação de",
      influencerApprovalAccent: "influenciadores",
      influencerApprovalDescription: "Todo cadastro começa como pendente. Aprove apenas perfis válidos para liberar a operação do programa.",
      registrationsCount: (count: number) => `${count} cadastros`,
      pendingPlural: "Pendentes",
      approvedPlural: "Aprovados",
      rejectedPlural: "Reprovados",
      suspendedPlural: "Suspensos",
      publicLink: "Link público",
      country: "País",
      city: "Cidade",
      network: "Rede",
      profile: "Perfil",
      followers: "Seguidores",
      categories: "Categorias",
      languages: "Idiomas",
      motivation: "Motivação",
      notInformed: "Não informado",
      noRegistrations: "Nenhum cadastro encontrado.",
      changeStatus: "Alterar status",
      statusDialogTitle: "Status do cadastro",
      approve: "Aprovar",
      approveDescription: "Libera o perfil para operar no programa.",
      reject: "Reprovar",
      rejectDescription: "Marca o cadastro como não aprovado.",
      suspend: "Suspender",
      suspendDescription: "Bloqueia temporariamente um perfil aprovado.",
      backToPending: "Voltar para pendente",
      backToPendingDescription: "Reabre o cadastro para nova revisão.",
      current: "atual",
    },
  },
  ptPt: {
    common: {
      logout: "Sair",
      program: "Programa",
      backToBio: "Voltar à bio",
      status: "Estado",
      pendingApproval: "A aguardar aprovação",
      approved: "Aprovado",
      rejected: "Reprovado",
      suspended: "Suspenso",
      pending: "Pendente",
      available: "Disponível",
      paid: "Pago",
      canceled: "Cancelado",
      code: "Código",
      viewAll: "Ver todos",
      admin: "Admin",
      active: "Ativo",
      inactive: "Inativo",
      moveUp: "Subir",
      moveDown: "Descer",
      edit: "Alterar",
      delete: "Excluir",
      cancel: "Cancelar",
      confirmDelete: "Confirmar eliminação",
      close: "Fechar",
    },
    adminHome: {
      eyebrow: "Painel administrativo",
      hello: "Olá,",
      description: "Reveja registos, acompanhe campanhas e mantenha o programa de influenciadores organizado.",
      statsInfluencers: "Influenciadores",
      statsWaiting: "A aguardar",
      statsApproved: "Aprovados",
      statsRejected: "Reprovados",
      reviewRegistrations: "Aprovar registos",
      reviewRegistrationsText: "Rever solicitações, aprovar, reprovar ou suspender perfis.",
      manageCampaigns: "Gerir campanhas",
      campaignsCount: (count: number) => `${count} campanhas disponíveis no programa.`,
      earnings: "Ganhos lançados",
      homeLinks: "Links da página inicial",
      homeLinksCount: (count: number) => `${count} atalhos ativos na home.`,
      documents: "Documentos e materiais",
      documentsCount: (count: number) => `${count} itens registados para influenciadores.`,
      latestRegistrations: "Últimos registos",
      influencersToReview: "Influenciadores para rever",
      emptyLatestRegistrations: "Nenhum registo para rever neste momento.",
    },
    account: {
      eyebrow: "Minha conta",
      dashboardEyebrow: "Painel FindB Europa",
      hello: "Olá,",
      description: "O seu link exclusivo, campanhas, materiais, ganhos e estatísticas numa área simples para partilhar.",
      accountDescription: "Aceda ao seu link, estado de aprovação, campanhas e materiais.",
      myLink: "O meu link",
      exclusiveUrl: "URL exclusiva",
      shareUrl: "Partilhe a sua URL exclusiva",
      shareHint: "Use este link em stories, grupos e publicações para registar os seus resultados.",
      clicks: "Cliques",
      registrations: "Registos",
      shares: "Partilhas",
      campaigns: "Campanhas",
      contentHub: "Central de conteúdo",
      statement: "Extrato",
      rankingChallenges: "Ranking e desafios",
      noEarnings: "Os seus ganhos aparecem aqui quando as campanhas forem validadas pela equipa.",
      weeklyRanking: "Ranking semanal",
      monthlyRanking: "Ranking mensal",
      specialMissions: "Missões especiais",
      referralBonus: "Bónus por indicação",
    },
    influencerLogin: {
      eyebrow: "Área do influenciador",
      title: "Minha conta",
      description: "Aceda ao seu link, estado de aprovação, campanhas e materiais.",
    },
    adminLinks: {
      newLink: "Novo link",
      eyebrow: "Página inicial",
      titleStart: "Links",
      titleAccent: "em destaque",
      description: "Registe, altere, elimine e organize a ordem dos cards exibidos na página inicial.",
      registered: "Links registados",
      activeHome: "Ativos na home",
      empty: "Nenhum link registado.",
      deleteTitle: "Eliminar link",
      deleteDescription: "Esta ação remove o card da página inicial e do painel administrativo.",
    },
    adminLists: {
      newEarning: "Novo ganho",
      earningsBack: "Ganhos",
      earningsEyebrow: "Ganhos lançados",
      earningsTitleStart: "Extrato de",
      earningsTitleAccent: "ganhos",
      earningsDescription: "Consulte os lançamentos feitos para influenciadores, campanhas associadas e estado de pagamento.",
      launchEarningTitleStart: "Lançar",
      launchEarningTitleAccent: "ganho",
      newEarningDescription: "Registe um valor para um influenciador sem misturar criação com a listagem do extrato.",
      earningFormTitle: "Lançar ganho",
      earningFormDescription: "Valores pendentes ou disponíveis atualizam o saldo do influenciador.",
      influencer: "Influenciador",
      select: "Selecione",
      campaign: "Campanha",
      amountEuros: "Valor em euros",
      earningExample: "Ex: Bónus da campanha de stories",
      savingEarning: "A lançar...",
      noCampaign: "Sem campanha",
      noEarnings: "Nenhum ganho lançado.",
      deleteEarningTitle: "Eliminar ganho",
      deleteEarningDescription: "Esta ação remove o lançamento e ajusta o saldo pendente ou disponível do influenciador quando necessário.",
      newCampaign: "Nova campanha",
      campaignsBack: "Campanhas",
      campaignsEyebrow: "Campanhas",
      campaignsTitleStart: "Gerir",
      campaignsTitleAccent: "campanhas ativas",
      campaignsDescription: "Registe, altere datas, encerre ou elimine campanhas exibidas para influenciadores.",
      createCampaignTitleStart: "Registar",
      createCampaignTitleAccent: "campanha",
      editCampaignEyebrow: "Alterar campanha",
      editCampaignTitleStart: "Editar",
      campaignFormTitle: "Dados da campanha",
      campaignFormDescription: "Campanhas ativas aparecem para influenciadores e na área pública do programa.",
      title: "Título",
      descriptionLabel: "Descrição",
      activeCampaigns: "Ativas",
      pausedDraft: "Pausadas/rascunho",
      endedCampaigns: "Encerradas",
      campaignActive: "Ativa",
      campaignPaused: "Pausada",
      campaignEnded: "Encerrada",
      campaignDraft: "Rascunho",
      objective: "Objetivo",
      material: "Material",
      rewardEuros: "Recompensa em euros",
      materialType: "Tipo de material",
      eventMaterial: "Evento",
      statusField: "Estado",
      start: "Início",
      end: "Fim",
      startDate: "Data de início",
      endDate: "Data de fim",
      endDateHelper: "Deixe vazio para campanha sem fim definido.",
      saving: "A guardar...",
      createCampaignSubmit: "Registar campanha",
      saveChanges: "Guardar alterações",
      noEndDate: "Sem data de fim",
      linkedEarnings: (count: number) => `${count} lançamentos de ganhos associados.`,
      noCampaigns: "Nenhuma campanha registada.",
      deleteCampaignTitle: "Eliminar campanha",
      deleteCampaignDescription: "Esta ação remove a campanha do admin e da área dos influenciadores. Os ganhos associados continuam guardados, mas sem campanha associada.",
      newDocument: "Novo documento",
      documentsBack: "Documentos",
      newMaterial: "Novo material",
      editMaterial: "Editar material",
      documentsEyebrow: "Materiais",
      documentsTitleStart: "Documentos",
      documentsTitleAccent: "do programa",
      documentsDescription: "Registe regulamentos, materiais para download e links para envio de conteúdo.",
      createDocumentTitleStart: "Registar",
      createDocumentTitleAccent: "documento",
      editDocumentTitleStart: "Alterar",
      editDocumentTitleAccent: "documento",
      documentFormTitle: "Dados do documento",
      documentFormDescription: "Registe links para regulamento, materiais de divulgação ou envio de conteúdo.",
      regulations: "Regulamentos",
      materials: "Materiais",
      submissions: "Envios",
      documentRegulation: "Regulamento",
      documentMaterial: "Material",
      documentMaterialDownload: "Material para baixar",
      documentSubmission: "Envio de conteúdo",
      documentStory: "Stories",
      documentScript: "Roteiro",
      documentBrand: "Marca / logótipos",
      documentOther: "Outro documento",
      documentFallback: "Documento",
      type: "Tipo",
      documentUrl: "URL do documento",
      documentUrlHelper: "Use um link interno, PDF, Google Drive, formulário ou ficheiro publicado.",
      createDocumentSubmit: "Registar documento",
      open: "Abrir",
      noDocuments: "Nenhum documento registado.",
      deleteDocumentTitle: "Eliminar documento",
      deleteDocumentDescription: "Esta ação remove o documento da área de influenciadores e do painel administrativo.",
      moderation: "Moderação",
      influencerApprovalStart: "Aprovação de",
      influencerApprovalAccent: "influenciadores",
      influencerApprovalDescription: "Todo registo começa como pendente. Aprove apenas perfis válidos para libertar a operação do programa.",
      registrationsCount: (count: number) => `${count} registos`,
      pendingPlural: "Pendentes",
      approvedPlural: "Aprovados",
      rejectedPlural: "Reprovados",
      suspendedPlural: "Suspensos",
      publicLink: "Link público",
      country: "País",
      city: "Cidade",
      network: "Rede",
      profile: "Perfil",
      followers: "Seguidores",
      categories: "Categorias",
      languages: "Idiomas",
      motivation: "Motivação",
      notInformed: "Não informado",
      noRegistrations: "Nenhum registo encontrado.",
      changeStatus: "Alterar estado",
      statusDialogTitle: "Estado do registo",
      approve: "Aprovar",
      approveDescription: "Liberta o perfil para operar no programa.",
      reject: "Reprovar",
      rejectDescription: "Marca o registo como não aprovado.",
      suspend: "Suspender",
      suspendDescription: "Bloqueia temporariamente um perfil aprovado.",
      backToPending: "Voltar para pendente",
      backToPendingDescription: "Reabre o registo para nova revisão.",
      current: "atual",
    },
  },
  en: {
    common: {
      logout: "Log out",
      program: "Program",
      backToBio: "Back to bio",
      status: "Status",
      pendingApproval: "Pending approval",
      approved: "Approved",
      rejected: "Rejected",
      suspended: "Suspended",
      pending: "Pending",
      available: "Available",
      paid: "Paid",
      canceled: "Canceled",
      code: "Code",
      viewAll: "View all",
      admin: "Admin",
      active: "Active",
      inactive: "Inactive",
      moveUp: "Move up",
      moveDown: "Move down",
      edit: "Edit",
      delete: "Delete",
      cancel: "Cancel",
      confirmDelete: "Confirm delete",
      close: "Close",
    },
    adminHome: {
      eyebrow: "Admin dashboard",
      hello: "Hello,",
      description: "Review applications, track campaigns, and keep the influencer program organized.",
      statsInfluencers: "Influencers",
      statsWaiting: "Waiting",
      statsApproved: "Approved",
      statsRejected: "Rejected",
      reviewRegistrations: "Approve applications",
      reviewRegistrationsText: "Review requests, approve, reject, or suspend profiles.",
      manageCampaigns: "Manage campaigns",
      campaignsCount: (count: number) => `${count} campaigns available in the program.`,
      earnings: "Posted earnings",
      homeLinks: "Homepage links",
      homeLinksCount: (count: number) => `${count} active homepage shortcuts.`,
      documents: "Documents and materials",
      documentsCount: (count: number) => `${count} items registered for influencers.`,
      latestRegistrations: "Latest applications",
      influencersToReview: "Influencers to review",
      emptyLatestRegistrations: "No applications to review right now.",
    },
    account: {
      eyebrow: "My account",
      dashboardEyebrow: "FindB Europa dashboard",
      hello: "Hello,",
      description: "Your exclusive link, campaigns, materials, earnings, and stats in one simple sharing area.",
      accountDescription: "Access your link, approval status, campaigns, and materials.",
      myLink: "My link",
      exclusiveUrl: "Exclusive URL",
      shareUrl: "Share your exclusive URL",
      shareHint: "Use this link in stories, groups, and posts to track your results.",
      clicks: "Clicks",
      registrations: "Signups",
      shares: "Shares",
      campaigns: "Campaigns",
      contentHub: "Content hub",
      statement: "Statement",
      rankingChallenges: "Ranking and challenges",
      noEarnings: "Your earnings appear here when campaigns are validated by the team.",
      weeklyRanking: "Weekly ranking",
      monthlyRanking: "Monthly ranking",
      specialMissions: "Special missions",
      referralBonus: "Referral bonus",
    },
    influencerLogin: {
      eyebrow: "Influencer area",
      title: "My account",
      description: "Access your link, approval status, campaigns, and materials.",
    },
    adminLinks: {
      newLink: "New link",
      eyebrow: "Homepage",
      titleStart: "Featured",
      titleAccent: "links",
      description: "Create, edit, delete, and organize the order of cards shown on the homepage.",
      registered: "Registered links",
      activeHome: "Active on home",
      empty: "No links registered.",
      deleteTitle: "Delete link",
      deleteDescription: "This action removes the card from the homepage and admin dashboard.",
    },
    adminLists: {
      newEarning: "New earning",
      earningsBack: "Earnings",
      earningsEyebrow: "Posted earnings",
      earningsTitleStart: "Earnings",
      earningsTitleAccent: "statement",
      earningsDescription: "Review influencer earnings, linked campaigns, and payment status.",
      launchEarningTitleStart: "Post",
      launchEarningTitleAccent: "earning",
      newEarningDescription: "Register an amount for an influencer without mixing creation with the statement list.",
      earningFormTitle: "Post earning",
      earningFormDescription: "Pending or available amounts update the influencer balance.",
      influencer: "Influencer",
      select: "Select",
      campaign: "Campaign",
      amountEuros: "Amount in euros",
      earningExample: "Ex: Stories campaign bonus",
      savingEarning: "Posting...",
      noCampaign: "No campaign",
      noEarnings: "No earnings posted.",
      deleteEarningTitle: "Delete earning",
      deleteEarningDescription: "This action removes the entry and adjusts the influencer's pending or available balance when needed.",
      newCampaign: "New campaign",
      campaignsBack: "Campaigns",
      campaignsEyebrow: "Campaigns",
      campaignsTitleStart: "Manage",
      campaignsTitleAccent: "active campaigns",
      campaignsDescription: "Create, edit dates, end, or delete campaigns shown to influencers.",
      createCampaignTitleStart: "Create",
      createCampaignTitleAccent: "campaign",
      editCampaignEyebrow: "Edit campaign",
      editCampaignTitleStart: "Edit",
      campaignFormTitle: "Campaign details",
      campaignFormDescription: "Active campaigns appear for influencers and in the program public area.",
      title: "Title",
      descriptionLabel: "Description",
      activeCampaigns: "Active",
      pausedDraft: "Paused/draft",
      endedCampaigns: "Ended",
      campaignActive: "Active",
      campaignPaused: "Paused",
      campaignEnded: "Ended",
      campaignDraft: "Draft",
      objective: "Objective",
      material: "Material",
      rewardEuros: "Reward in euros",
      materialType: "Material type",
      eventMaterial: "Event",
      statusField: "Status",
      start: "Start",
      end: "End",
      startDate: "Start date",
      endDate: "End date",
      endDateHelper: "Leave empty for a campaign without a defined end.",
      saving: "Saving...",
      createCampaignSubmit: "Create campaign",
      saveChanges: "Save changes",
      noEndDate: "No end date",
      linkedEarnings: (count: number) => `${count} linked earning entries.`,
      noCampaigns: "No campaigns registered.",
      deleteCampaignTitle: "Delete campaign",
      deleteCampaignDescription: "This action removes the campaign from admin and the influencer area. Linked earnings remain stored without an associated campaign.",
      newDocument: "New document",
      documentsBack: "Documents",
      newMaterial: "New material",
      editMaterial: "Edit material",
      documentsEyebrow: "Materials",
      documentsTitleStart: "Program",
      documentsTitleAccent: "documents",
      documentsDescription: "Register rules, download materials, and content submission links.",
      createDocumentTitleStart: "Create",
      createDocumentTitleAccent: "document",
      editDocumentTitleStart: "Edit",
      editDocumentTitleAccent: "document",
      documentFormTitle: "Document details",
      documentFormDescription: "Register links for rules, promotional materials, or content submission.",
      regulations: "Rules",
      materials: "Materials",
      submissions: "Submissions",
      documentRegulation: "Rules",
      documentMaterial: "Material",
      documentMaterialDownload: "Download material",
      documentSubmission: "Content submission",
      documentStory: "Stories",
      documentScript: "Script",
      documentBrand: "Brand / logos",
      documentOther: "Other document",
      documentFallback: "Document",
      type: "Type",
      documentUrl: "Document URL",
      documentUrlHelper: "Use an internal link, PDF, Google Drive, form, or published file.",
      createDocumentSubmit: "Create document",
      open: "Open",
      noDocuments: "No documents registered.",
      deleteDocumentTitle: "Delete document",
      deleteDocumentDescription: "This action removes the document from the influencer area and admin dashboard.",
      moderation: "Moderation",
      influencerApprovalStart: "Influencer",
      influencerApprovalAccent: "approval",
      influencerApprovalDescription: "Every application starts as pending. Approve only valid profiles to unlock program operations.",
      registrationsCount: (count: number) => `${count} applications`,
      pendingPlural: "Pending",
      approvedPlural: "Approved",
      rejectedPlural: "Rejected",
      suspendedPlural: "Suspended",
      publicLink: "Public link",
      country: "Country",
      city: "City",
      network: "Network",
      profile: "Profile",
      followers: "Followers",
      categories: "Categories",
      languages: "Languages",
      motivation: "Motivation",
      notInformed: "Not informed",
      noRegistrations: "No applications found.",
      changeStatus: "Change status",
      statusDialogTitle: "Application status",
      approve: "Approve",
      approveDescription: "Allows the profile to operate in the program.",
      reject: "Reject",
      rejectDescription: "Marks the application as not approved.",
      suspend: "Suspend",
      suspendDescription: "Temporarily blocks an approved profile.",
      backToPending: "Back to pending",
      backToPendingDescription: "Reopens the application for a new review.",
      current: "current",
    },
  },
  es: {
    common: {
      logout: "Salir",
      program: "Programa",
      backToBio: "Volver a la bio",
      status: "Estado",
      pendingApproval: "Pendiente de aprobación",
      approved: "Aprobado",
      rejected: "Rechazado",
      suspended: "Suspendido",
      pending: "Pendiente",
      available: "Disponible",
      paid: "Pagado",
      canceled: "Cancelado",
      code: "Código",
      viewAll: "Ver todos",
      admin: "Admin",
      active: "Activo",
      inactive: "Inactivo",
      moveUp: "Subir",
      moveDown: "Bajar",
      edit: "Editar",
      delete: "Eliminar",
      cancel: "Cancelar",
      confirmDelete: "Confirmar eliminación",
      close: "Cerrar",
    },
    adminHome: {
      eyebrow: "Panel administrativo",
      hello: "Hola,",
      description: "Revisa solicitudes, acompaña campañas y mantén organizado el programa de influencers.",
      statsInfluencers: "Influencers",
      statsWaiting: "En espera",
      statsApproved: "Aprobados",
      statsRejected: "Rechazados",
      reviewRegistrations: "Aprobar solicitudes",
      reviewRegistrationsText: "Revisar solicitudes, aprobar, rechazar o suspender perfiles.",
      manageCampaigns: "Gestionar campañas",
      campaignsCount: (count: number) => `${count} campañas disponibles en el programa.`,
      earnings: "Ganancias registradas",
      homeLinks: "Links de la página inicial",
      homeLinksCount: (count: number) => `${count} accesos activos en la home.`,
      documents: "Documentos y materiales",
      documentsCount: (count: number) => `${count} ítems registrados para influencers.`,
      latestRegistrations: "Últimas solicitudes",
      influencersToReview: "Influencers para revisar",
      emptyLatestRegistrations: "No hay solicitudes para revisar en este momento.",
    },
    account: {
      eyebrow: "Mi cuenta",
      dashboardEyebrow: "Panel FindB Europa",
      hello: "Hola,",
      description: "Tu link exclusivo, campañas, materiales, ganancias y estadísticas en un área simple para compartir.",
      accountDescription: "Accede a tu link, estado de aprobación, campañas y materiales.",
      myLink: "Mi link",
      exclusiveUrl: "URL exclusiva",
      shareUrl: "Comparte tu URL exclusiva",
      shareHint: "Usa este link en stories, grupos y publicaciones para registrar tus resultados.",
      clicks: "Clics",
      registrations: "Registros",
      shares: "Compartidos",
      campaigns: "Campañas",
      contentHub: "Central de contenido",
      statement: "Extracto",
      rankingChallenges: "Ranking y desafíos",
      noEarnings: "Tus ganancias aparecen aquí cuando el equipo valide las campañas.",
      weeklyRanking: "Ranking semanal",
      monthlyRanking: "Ranking mensual",
      specialMissions: "Misiones especiales",
      referralBonus: "Bono por indicación",
    },
    influencerLogin: {
      eyebrow: "Área del influencer",
      title: "Mi cuenta",
      description: "Accede a tu link, estado de aprobación, campañas y materiales.",
    },
    adminLinks: {
      newLink: "Nuevo link",
      eyebrow: "Página inicial",
      titleStart: "Links",
      titleAccent: "destacados",
      description: "Crea, edita, elimina y organiza el orden de las tarjetas mostradas en la página inicial.",
      registered: "Links registrados",
      activeHome: "Activos en la home",
      empty: "No hay links registrados.",
      deleteTitle: "Eliminar link",
      deleteDescription: "Esta acción elimina la tarjeta de la página inicial y del panel administrativo.",
    },
    adminLists: {
      newEarning: "Nueva ganancia",
      earningsBack: "Ganancias",
      earningsEyebrow: "Ganancias registradas",
      earningsTitleStart: "Extracto de",
      earningsTitleAccent: "ganancias",
      earningsDescription: "Consulta los registros de influencers, campañas vinculadas y estado de pago.",
      launchEarningTitleStart: "Registrar",
      launchEarningTitleAccent: "ganancia",
      newEarningDescription: "Registra un valor para un influencer sin mezclar la creación con la lista del extracto.",
      earningFormTitle: "Registrar ganancia",
      earningFormDescription: "Los valores pendientes o disponibles actualizan el saldo del influencer.",
      influencer: "Influencer",
      select: "Selecciona",
      campaign: "Campaña",
      amountEuros: "Valor en euros",
      earningExample: "Ej: Bono de la campaña de stories",
      savingEarning: "Registrando...",
      noCampaign: "Sin campaña",
      noEarnings: "No hay ganancias registradas.",
      deleteEarningTitle: "Eliminar ganancia",
      deleteEarningDescription: "Esta acción elimina el registro y ajusta el saldo pendiente o disponible del influencer cuando sea necesario.",
      newCampaign: "Nueva campaña",
      campaignsBack: "Campañas",
      campaignsEyebrow: "Campañas",
      campaignsTitleStart: "Gestionar",
      campaignsTitleAccent: "campañas activas",
      campaignsDescription: "Crea, edita fechas, finaliza o elimina campañas mostradas a influencers.",
      createCampaignTitleStart: "Crear",
      createCampaignTitleAccent: "campaña",
      editCampaignEyebrow: "Editar campaña",
      editCampaignTitleStart: "Editar",
      campaignFormTitle: "Datos de la campaña",
      campaignFormDescription: "Las campañas activas aparecen para influencers y en el área pública del programa.",
      title: "Título",
      descriptionLabel: "Descripción",
      activeCampaigns: "Activas",
      pausedDraft: "Pausadas/borrador",
      endedCampaigns: "Finalizadas",
      campaignActive: "Activa",
      campaignPaused: "Pausada",
      campaignEnded: "Finalizada",
      campaignDraft: "Borrador",
      objective: "Objetivo",
      material: "Material",
      rewardEuros: "Recompensa en euros",
      materialType: "Tipo de material",
      eventMaterial: "Evento",
      statusField: "Estado",
      start: "Inicio",
      end: "Fin",
      startDate: "Fecha de inicio",
      endDate: "Fecha de fin",
      endDateHelper: "Déjalo vacío para una campaña sin fin definido.",
      saving: "Guardando...",
      createCampaignSubmit: "Crear campaña",
      saveChanges: "Guardar cambios",
      noEndDate: "Sin fecha de fin",
      linkedEarnings: (count: number) => `${count} registros de ganancias vinculados.`,
      noCampaigns: "No hay campañas registradas.",
      deleteCampaignTitle: "Eliminar campaña",
      deleteCampaignDescription: "Esta acción elimina la campaña del admin y del área de influencers. Las ganancias vinculadas siguen guardadas, pero sin campaña asociada.",
      newDocument: "Nuevo documento",
      documentsBack: "Documentos",
      newMaterial: "Nuevo material",
      editMaterial: "Editar material",
      documentsEyebrow: "Materiales",
      documentsTitleStart: "Documentos",
      documentsTitleAccent: "del programa",
      documentsDescription: "Registra reglamentos, materiales para descargar y links de envío de contenido.",
      createDocumentTitleStart: "Crear",
      createDocumentTitleAccent: "documento",
      editDocumentTitleStart: "Editar",
      editDocumentTitleAccent: "documento",
      documentFormTitle: "Datos del documento",
      documentFormDescription: "Registra links para reglamentos, materiales de divulgación o envío de contenido.",
      regulations: "Reglamentos",
      materials: "Materiales",
      submissions: "Envíos",
      documentRegulation: "Reglamento",
      documentMaterial: "Material",
      documentMaterialDownload: "Material para descargar",
      documentSubmission: "Envío de contenido",
      documentStory: "Stories",
      documentScript: "Guion",
      documentBrand: "Marca / logotipos",
      documentOther: "Otro documento",
      documentFallback: "Documento",
      type: "Tipo",
      documentUrl: "URL del documento",
      documentUrlHelper: "Usa un link interno, PDF, Google Drive, formulario o archivo publicado.",
      createDocumentSubmit: "Crear documento",
      open: "Abrir",
      noDocuments: "No hay documentos registrados.",
      deleteDocumentTitle: "Eliminar documento",
      deleteDocumentDescription: "Esta acción elimina el documento del área de influencers y del panel administrativo.",
      moderation: "Moderación",
      influencerApprovalStart: "Aprobación de",
      influencerApprovalAccent: "influencers",
      influencerApprovalDescription: "Todo registro empieza como pendiente. Aprueba solo perfiles válidos para liberar la operación del programa.",
      registrationsCount: (count: number) => `${count} registros`,
      pendingPlural: "Pendientes",
      approvedPlural: "Aprobados",
      rejectedPlural: "Rechazados",
      suspendedPlural: "Suspendidos",
      publicLink: "Link público",
      country: "País",
      city: "Ciudad",
      network: "Red",
      profile: "Perfil",
      followers: "Seguidores",
      categories: "Categorías",
      languages: "Idiomas",
      motivation: "Motivación",
      notInformed: "No informado",
      noRegistrations: "No se encontraron registros.",
      changeStatus: "Cambiar estado",
      statusDialogTitle: "Estado del registro",
      approve: "Aprobar",
      approveDescription: "Libera el perfil para operar en el programa.",
      reject: "Rechazar",
      rejectDescription: "Marca el registro como no aprobado.",
      suspend: "Suspender",
      suspendDescription: "Bloquea temporalmente un perfil aprobado.",
      backToPending: "Volver a pendiente",
      backToPendingDescription: "Reabre el registro para una nueva revisión.",
      current: "actual",
    },
  },
  fr: {
    common: {
      logout: "Sortir",
      program: "Programme",
      backToBio: "Retour à la bio",
      status: "Statut",
      pendingApproval: "En attente d’approbation",
      approved: "Approuvé",
      rejected: "Refusé",
      suspended: "Suspendu",
      pending: "En attente",
      available: "Disponible",
      paid: "Payé",
      canceled: "Annulé",
      code: "Code",
      viewAll: "Voir tout",
      admin: "Admin",
      active: "Actif",
      inactive: "Inactif",
      moveUp: "Monter",
      moveDown: "Descendre",
      edit: "Modifier",
      delete: "Supprimer",
      cancel: "Annuler",
      confirmDelete: "Confirmer la suppression",
      close: "Fermer",
    },
    adminHome: {
      eyebrow: "Tableau de bord admin",
      hello: "Bonjour,",
      description: "Examinez les inscriptions, suivez les campagnes et gardez le programme d’influenceurs organisé.",
      statsInfluencers: "Influenceurs",
      statsWaiting: "En attente",
      statsApproved: "Approuvés",
      statsRejected: "Refusés",
      reviewRegistrations: "Approuver les inscriptions",
      reviewRegistrationsText: "Examiner les demandes, approuver, refuser ou suspendre des profils.",
      manageCampaigns: "Gérer les campagnes",
      campaignsCount: (count: number) => `${count} campagnes disponibles dans le programme.`,
      earnings: "Gains publiés",
      homeLinks: "Liens de la page d’accueil",
      homeLinksCount: (count: number) => `${count} raccourcis actifs sur la home.`,
      documents: "Documents et supports",
      documentsCount: (count: number) => `${count} éléments enregistrés pour les influenceurs.`,
      latestRegistrations: "Dernières inscriptions",
      influencersToReview: "Influenceurs à examiner",
      emptyLatestRegistrations: "Aucune inscription à examiner pour le moment.",
    },
    account: {
      eyebrow: "Mon compte",
      dashboardEyebrow: "Tableau de bord FindB Europa",
      hello: "Bonjour,",
      description: "Votre lien exclusif, campagnes, supports, gains et statistiques dans un espace simple à partager.",
      accountDescription: "Accédez à votre lien, statut d’approbation, campagnes et supports.",
      myLink: "Mon lien",
      exclusiveUrl: "URL exclusive",
      shareUrl: "Partagez votre URL exclusive",
      shareHint: "Utilisez ce lien dans les stories, groupes et publications pour suivre vos résultats.",
      clicks: "Clics",
      registrations: "Inscriptions",
      shares: "Partages",
      campaigns: "Campagnes",
      contentHub: "Centre de contenu",
      statement: "Relevé",
      rankingChallenges: "Classement et défis",
      noEarnings: "Vos gains apparaissent ici lorsque les campagnes sont validées par l’équipe.",
      weeklyRanking: "Classement hebdomadaire",
      monthlyRanking: "Classement mensuel",
      specialMissions: "Missions spéciales",
      referralBonus: "Bonus de parrainage",
    },
    influencerLogin: {
      eyebrow: "Espace influenceur",
      title: "Mon compte",
      description: "Accédez à votre lien, statut d’approbation, campagnes et supports.",
    },
    adminLinks: {
      newLink: "Nouveau lien",
      eyebrow: "Page d’accueil",
      titleStart: "Liens",
      titleAccent: "en vedette",
      description: "Créez, modifiez, supprimez et organisez l’ordre des cartes affichées sur la page d’accueil.",
      registered: "Liens enregistrés",
      activeHome: "Actifs sur la home",
      empty: "Aucun lien enregistré.",
      deleteTitle: "Supprimer le lien",
      deleteDescription: "Cette action supprime la carte de la page d’accueil et du tableau de bord admin.",
    },
    adminLists: {
      newEarning: "Nouveau gain",
      earningsBack: "Gains",
      earningsEyebrow: "Gains publiés",
      earningsTitleStart: "Relevé des",
      earningsTitleAccent: "gains",
      earningsDescription: "Consultez les gains des influenceurs, les campagnes liées et le statut de paiement.",
      launchEarningTitleStart: "Publier",
      launchEarningTitleAccent: "gain",
      newEarningDescription: "Enregistrez un montant pour un influenceur sans mélanger la création avec la liste du relevé.",
      earningFormTitle: "Publier un gain",
      earningFormDescription: "Les montants en attente ou disponibles mettent à jour le solde de l’influenceur.",
      influencer: "Influenceur",
      select: "Sélectionner",
      campaign: "Campagne",
      amountEuros: "Montant en euros",
      earningExample: "Ex : bonus de campagne stories",
      savingEarning: "Publication...",
      noCampaign: "Sans campagne",
      noEarnings: "Aucun gain publié.",
      deleteEarningTitle: "Supprimer le gain",
      deleteEarningDescription: "Cette action supprime l’entrée et ajuste le solde en attente ou disponible de l’influenceur si nécessaire.",
      newCampaign: "Nouvelle campagne",
      campaignsBack: "Campagnes",
      campaignsEyebrow: "Campagnes",
      campaignsTitleStart: "Gérer les",
      campaignsTitleAccent: "campagnes actives",
      campaignsDescription: "Créez, modifiez les dates, terminez ou supprimez les campagnes affichées aux influenceurs.",
      createCampaignTitleStart: "Créer",
      createCampaignTitleAccent: "campagne",
      editCampaignEyebrow: "Modifier la campagne",
      editCampaignTitleStart: "Modifier",
      campaignFormTitle: "Données de la campagne",
      campaignFormDescription: "Les campagnes actives apparaissent aux influenceurs et dans l’espace public du programme.",
      title: "Titre",
      descriptionLabel: "Description",
      activeCampaigns: "Actives",
      pausedDraft: "En pause/brouillon",
      endedCampaigns: "Terminées",
      campaignActive: "Active",
      campaignPaused: "En pause",
      campaignEnded: "Terminée",
      campaignDraft: "Brouillon",
      objective: "Objectif",
      material: "Support",
      rewardEuros: "Récompense en euros",
      materialType: "Type de support",
      eventMaterial: "Événement",
      statusField: "Statut",
      start: "Début",
      end: "Fin",
      startDate: "Date de début",
      endDate: "Date de fin",
      endDateHelper: "Laissez vide pour une campagne sans fin définie.",
      saving: "Enregistrement...",
      createCampaignSubmit: "Créer la campagne",
      saveChanges: "Enregistrer les modifications",
      noEndDate: "Sans date de fin",
      linkedEarnings: (count: number) => `${count} entrées de gains liées.`,
      noCampaigns: "Aucune campagne enregistrée.",
      deleteCampaignTitle: "Supprimer la campagne",
      deleteCampaignDescription: "Cette action supprime la campagne de l’admin et de l’espace influenceur. Les gains liés restent enregistrés, mais sans campagne associée.",
      newDocument: "Nouveau document",
      documentsBack: "Documents",
      newMaterial: "Nouveau support",
      editMaterial: "Modifier le support",
      documentsEyebrow: "Supports",
      documentsTitleStart: "Documents",
      documentsTitleAccent: "du programme",
      documentsDescription: "Enregistrez les règles, supports à télécharger et liens d’envoi de contenu.",
      createDocumentTitleStart: "Créer",
      createDocumentTitleAccent: "document",
      editDocumentTitleStart: "Modifier",
      editDocumentTitleAccent: "document",
      documentFormTitle: "Données du document",
      documentFormDescription: "Enregistrez des liens vers le règlement, les supports de promotion ou l’envoi de contenu.",
      regulations: "Règlements",
      materials: "Supports",
      submissions: "Envois",
      documentRegulation: "Règlement",
      documentMaterial: "Support",
      documentMaterialDownload: "Support à télécharger",
      documentSubmission: "Envoi de contenu",
      documentStory: "Stories",
      documentScript: "Script",
      documentBrand: "Marque / logos",
      documentOther: "Autre document",
      documentFallback: "Document",
      type: "Type",
      documentUrl: "URL du document",
      documentUrlHelper: "Utilisez un lien interne, PDF, Google Drive, formulaire ou fichier publié.",
      createDocumentSubmit: "Créer le document",
      open: "Ouvrir",
      noDocuments: "Aucun document enregistré.",
      deleteDocumentTitle: "Supprimer le document",
      deleteDocumentDescription: "Cette action supprime le document de l’espace influenceur et du tableau de bord admin.",
      moderation: "Modération",
      influencerApprovalStart: "Approbation des",
      influencerApprovalAccent: "influenceurs",
      influencerApprovalDescription: "Chaque inscription commence en attente. Approuvez uniquement les profils valides pour lancer les opérations du programme.",
      registrationsCount: (count: number) => `${count} inscriptions`,
      pendingPlural: "En attente",
      approvedPlural: "Approuvés",
      rejectedPlural: "Refusés",
      suspendedPlural: "Suspendus",
      publicLink: "Lien public",
      country: "Pays",
      city: "Ville",
      network: "Réseau",
      profile: "Profil",
      followers: "Abonnés",
      categories: "Catégories",
      languages: "Langues",
      motivation: "Motivation",
      notInformed: "Non renseigné",
      noRegistrations: "Aucune inscription trouvée.",
      changeStatus: "Changer le statut",
      statusDialogTitle: "Statut de l’inscription",
      approve: "Approuver",
      approveDescription: "Permet au profil d’opérer dans le programme.",
      reject: "Refuser",
      rejectDescription: "Marque l’inscription comme non approuvée.",
      suspend: "Suspendre",
      suspendDescription: "Bloque temporairement un profil approuvé.",
      backToPending: "Revenir en attente",
      backToPendingDescription: "Rouvre l’inscription pour un nouvel examen.",
      current: "actuel",
    },
  },
} as const

function normalizeLang(value?: string): ServerLang {
  if (value === "ptPt" || value === "en" || value === "es" || value === "fr") {
    return value
  }

  return "ptBr"
}

export async function getServerCopy() {
  const cookieStore = await cookies()
  return copy[normalizeLang(cookieStore.get("findb-lang")?.value)]
}

export async function getServerLang() {
  const cookieStore = await cookies()
  return normalizeLang(cookieStore.get("findb-lang")?.value)
}

export const publicInfluencerCopy: Record<
  ServerLang,
  {
    dashboard: string
    eyebrow: string
    titleStart: string
    titleAccent: string
    description: string
    cta: string
    highlights: string[]
    whoCanJoinTitle: string
    whoCanJoinItems: string[]
    earningWaysTitle: string
    earningWaysItems: string[]
    benefitsTitle: string
    benefitsItems: string[]
    influencerArea: string
    dashboardMenu: string
    menuItems: Array<[string, string]>
    availableCampaigns: string
    quickRegulation: string
    quickMaterials: string
    quickSubmit: string
    acceptedCountriesTitle: string
    acceptedCountriesText: (countries: string) => string
  }
> = {
  ptBr: {
    dashboard: "Meu painel",
    eyebrow: "FindB Europa",
    titleStart: "Influenciadores",
    titleAccent: "Imigrantes",
    description: "Divulgue a FindB Europa, ajude outros imigrantes a encontrarem oportunidades e acompanhe campanhas para ganhar em euros.",
    cta: "Quero ganhar em euros",
    highlights: ["Cadastro com aprovação", "Link exclusivo", "Pagamentos em euros"],
    whoCanJoinTitle: "Quem pode participar",
    whoCanJoinItems: ["Brasileiros residentes na Europa", "Imigrantes em qualquer país europeu", "Criadores, administradores de grupos e pessoas comuns", "Não precisa ter milhares de seguidores"],
    earningWaysTitle: "Formas de ganhar",
    earningWaysItems: ["Cadastro de novos usuários", "Divulgação da marca", "Vídeos, Reels e Stories marcando a FindB Europa", "Compartilhamento do link exclusivo", "Campanhas especiais, lives e eventos presenciais", "Indicação de novos influenciadores aprovados"],
    benefitsTitle: "Benefícios",
    benefitsItems: ["Pagamentos em euros", "Materiais oficiais gratuitos", "Campanhas com objetivos claros", "Painel de desempenho", "Programa de embaixadores", "Suporte dedicado"],
    influencerArea: "Área do influenciador",
    dashboardMenu: "Menu do painel",
    menuItems: [["Dashboard", "Resultados, ganhos, campanhas e estatísticas."], ["Meu Perfil", "Dados, redes sociais, categorias, idiomas e documentação."], ["Meu Link", "Copiar link, gerar QR Code, compartilhar e personalizar URL."], ["Campanhas", "Valores, prazos, objetivos, materiais e status."], ["Central de Conteúdo", "Vídeos, fotos, logos, stories, reels, textos e hashtags."], ["Ganhos", "Saldo disponível, pendente, extrato e próximos pagamentos."], ["Ranking", "Ranking semanal, mensal, anual, conquistas e badges."], ["Desafios", "Missões especiais, bônus e campanhas sazonais."]],
    availableCampaigns: "Campanhas disponíveis",
    quickRegulation: "Ver regulamento",
    quickMaterials: "Baixar materiais",
    quickSubmit: "Enviar conteúdo",
    acceptedCountriesTitle: "Países aceitos",
    acceptedCountriesText: (countries) => `Programa exclusivo para imigrantes residentes na Europa, incluindo ${countries} e demais países europeus onde a FindB Europa atua.`,
  },
  ptPt: {
    dashboard: "O meu painel",
    eyebrow: "FindB Europa",
    titleStart: "Influenciadores",
    titleAccent: "Imigrantes",
    description: "Divulgue a FindB Europa, ajude outros imigrantes a encontrarem oportunidades e acompanhe campanhas para ganhar em euros.",
    cta: "Quero ganhar em euros",
    highlights: ["Registo com aprovação", "Link exclusivo", "Pagamentos em euros"],
    whoCanJoinTitle: "Quem pode participar",
    whoCanJoinItems: ["Brasileiros residentes na Europa", "Imigrantes em qualquer país europeu", "Criadores, administradores de grupos e pessoas comuns", "Não precisa de ter milhares de seguidores"],
    earningWaysTitle: "Formas de ganhar",
    earningWaysItems: ["Registo de novos utilizadores", "Divulgação da marca", "Vídeos, Reels e Stories a marcar a FindB Europa", "Partilha do link exclusivo", "Campanhas especiais, lives e eventos presenciais", "Indicação de novos influenciadores aprovados"],
    benefitsTitle: "Benefícios",
    benefitsItems: ["Pagamentos em euros", "Materiais oficiais gratuitos", "Campanhas com objetivos claros", "Painel de desempenho", "Programa de embaixadores", "Suporte dedicado"],
    influencerArea: "Área do influenciador",
    dashboardMenu: "Menu do painel",
    menuItems: [["Dashboard", "Resultados, ganhos, campanhas e estatísticas."], ["O meu perfil", "Dados, redes sociais, categorias, idiomas e documentação."], ["O meu link", "Copiar link, gerar QR Code, partilhar e personalizar URL."], ["Campanhas", "Valores, prazos, objetivos, materiais e estado."], ["Central de conteúdo", "Vídeos, fotos, logos, stories, reels, textos e hashtags."], ["Ganhos", "Saldo disponível, pendente, extrato e próximos pagamentos."], ["Ranking", "Ranking semanal, mensal, anual, conquistas e badges."], ["Desafios", "Missões especiais, bónus e campanhas sazonais."]],
    availableCampaigns: "Campanhas disponíveis",
    quickRegulation: "Ver regulamento",
    quickMaterials: "Baixar materiais",
    quickSubmit: "Enviar conteúdo",
    acceptedCountriesTitle: "Países aceites",
    acceptedCountriesText: (countries) => `Programa exclusivo para imigrantes residentes na Europa, incluindo ${countries} e demais países europeus onde a FindB Europa atua.`,
  },
  en: {
    dashboard: "My dashboard",
    eyebrow: "FindB Europa",
    titleStart: "Immigrant",
    titleAccent: "Influencers",
    description: "Share FindB Europa, help other immigrants find opportunities, and follow campaigns to earn in euros.",
    cta: "I want to earn in euros",
    highlights: ["Approval-based signup", "Exclusive link", "Payments in euros"],
    whoCanJoinTitle: "Who can join",
    whoCanJoinItems: ["Brazilians living in Europe", "Immigrants in any European country", "Creators, group admins, and community members", "You do not need thousands of followers"],
    earningWaysTitle: "Ways to earn",
    earningWaysItems: ["New user signups", "Brand promotion", "Videos, Reels, and Stories tagging FindB Europa", "Sharing your exclusive link", "Special campaigns, lives, and in-person events", "Referrals of new approved influencers"],
    benefitsTitle: "Benefits",
    benefitsItems: ["Payments in euros", "Free official materials", "Campaigns with clear goals", "Performance dashboard", "Ambassador program", "Dedicated support"],
    influencerArea: "Influencer area",
    dashboardMenu: "Dashboard menu",
    menuItems: [["Dashboard", "Results, earnings, campaigns, and statistics."], ["My profile", "Personal data, social networks, categories, languages, and documentation."], ["My link", "Copy link, generate QR Code, share, and customize URL."], ["Campaigns", "Amounts, deadlines, goals, materials, and status."], ["Content hub", "Videos, photos, logos, stories, reels, text, and hashtags."], ["Earnings", "Available balance, pending balance, statement, and next payments."], ["Ranking", "Weekly, monthly, and annual rankings, achievements, and badges."], ["Challenges", "Special missions, bonuses, and seasonal campaigns."]],
    availableCampaigns: "Available campaigns",
    quickRegulation: "View rules",
    quickMaterials: "Download materials",
    quickSubmit: "Submit content",
    acceptedCountriesTitle: "Accepted countries",
    acceptedCountriesText: (countries) => `Exclusive program for immigrants living in Europe, including ${countries} and other European countries where FindB Europa operates.`,
  },
  es: {
    dashboard: "Mi panel",
    eyebrow: "FindB Europa",
    titleStart: "Influencers",
    titleAccent: "Inmigrantes",
    description: "Comparte FindB Europa, ayuda a otros inmigrantes a encontrar oportunidades y acompaña campañas para ganar en euros.",
    cta: "Quiero ganar en euros",
    highlights: ["Registro con aprobación", "Link exclusivo", "Pagos en euros"],
    whoCanJoinTitle: "Quién puede participar",
    whoCanJoinItems: ["Brasileños residentes en Europa", "Inmigrantes en cualquier país europeo", "Creadores, administradores de grupos y miembros de la comunidad", "No necesitas tener miles de seguidores"],
    earningWaysTitle: "Formas de ganar",
    earningWaysItems: ["Registro de nuevos usuarios", "Divulgación de la marca", "Videos, Reels y Stories etiquetando a FindB Europa", "Compartir el link exclusivo", "Campañas especiales, lives y eventos presenciales", "Indicación de nuevos influencers aprobados"],
    benefitsTitle: "Beneficios",
    benefitsItems: ["Pagos en euros", "Materiales oficiales gratuitos", "Campañas con objetivos claros", "Panel de desempeño", "Programa de embajadores", "Soporte dedicado"],
    influencerArea: "Área del influencer",
    dashboardMenu: "Menú del panel",
    menuItems: [["Dashboard", "Resultados, ganancias, campañas y estadísticas."], ["Mi perfil", "Datos, redes sociales, categorías, idiomas y documentación."], ["Mi link", "Copiar link, generar QR Code, compartir y personalizar URL."], ["Campañas", "Valores, plazos, objetivos, materiales y estado."], ["Central de contenido", "Videos, fotos, logos, stories, reels, textos y hashtags."], ["Ganancias", "Saldo disponible, pendiente, extracto y próximos pagos."], ["Ranking", "Ranking semanal, mensual, anual, conquistas y badges."], ["Desafíos", "Misiones especiales, bonos y campañas de temporada."]],
    availableCampaigns: "Campañas disponibles",
    quickRegulation: "Ver reglamento",
    quickMaterials: "Descargar materiales",
    quickSubmit: "Enviar contenido",
    acceptedCountriesTitle: "Países aceptados",
    acceptedCountriesText: (countries) => `Programa exclusivo para inmigrantes residentes en Europa, incluyendo ${countries} y demás países europeos donde FindB Europa actúa.`,
  },
  fr: {
    dashboard: "Mon tableau",
    eyebrow: "FindB Europa",
    titleStart: "Influenceurs",
    titleAccent: "immigrants",
    description: "Partagez FindB Europa, aidez d'autres immigrants à trouver des opportunités et suivez des campagnes pour gagner en euros.",
    cta: "Je veux gagner en euros",
    highlights: ["Inscription avec approbation", "Lien exclusif", "Paiements en euros"],
    whoCanJoinTitle: "Qui peut participer",
    whoCanJoinItems: ["Brésiliens résidant en Europe", "Immigrants dans tout pays européen", "Créateurs, administrateurs de groupes et membres de la communauté", "Pas besoin d'avoir des milliers d'abonnés"],
    earningWaysTitle: "Façons de gagner",
    earningWaysItems: ["Inscriptions de nouveaux utilisateurs", "Promotion de la marque", "Vidéos, Reels et Stories en identifiant FindB Europa", "Partage du lien exclusif", "Campagnes spéciales, lives et événements en présentiel", "Parrainage de nouveaux influenceurs approuvés"],
    benefitsTitle: "Avantages",
    benefitsItems: ["Paiements en euros", "Supports officiels gratuits", "Campagnes avec objectifs clairs", "Tableau de performance", "Programme d'ambassadeurs", "Support dédié"],
    influencerArea: "Espace influenceur",
    dashboardMenu: "Menu du tableau",
    menuItems: [["Dashboard", "Résultats, gains, campagnes et statistiques."], ["Mon profil", "Données, réseaux sociaux, catégories, langues et documentation."], ["Mon lien", "Copier le lien, générer un QR Code, partager et personnaliser l'URL."], ["Campagnes", "Montants, délais, objectifs, supports et statut."], ["Centre de contenu", "Vidéos, photos, logos, stories, reels, textes et hashtags."], ["Gains", "Solde disponible, en attente, relevé et prochains paiements."], ["Classement", "Classements hebdomadaire, mensuel, annuel, réussites et badges."], ["Défis", "Missions spéciales, bonus et campagnes saisonnières."]],
    availableCampaigns: "Campagnes disponibles",
    quickRegulation: "Voir le règlement",
    quickMaterials: "Télécharger les supports",
    quickSubmit: "Envoyer du contenu",
    acceptedCountriesTitle: "Pays acceptés",
    acceptedCountriesText: (countries) => `Programme exclusif pour les immigrants résidant en Europe, y compris ${countries} et les autres pays européens où FindB Europa opère.`,
  },
}

export const adminSchedulingCopy: Record<
  ServerLang,
  {
    back: string
    eyebrow: string
    titleStart: string
    titleAccent: string
    description: string
    released: string
    available: string
    reserved: string
    formTitle: string
    formDescription: string
    date: string
    time: string
    duration: string
    minutes: (count: number) => string
    oneHour: string
    oneHourThirty: string
    internalNote: string
    optional: string
    saving: string
    createSlot: string
    nextSlotsEyebrow: string
    configuredSchedule: string
    reservedStatus: string
    availableStatus: string
    inactiveStatus: string
    fromTo: (start: string, end: string) => string
    activate: string
    deactivate: string
    delete: string
    noFutureSlots: string
    requestsEyebrow: string
    scheduledMeetings: string
    adminShortcutTitle: string
    adminShortcutSubtitle: (count: number) => string
    cancelMeeting: string
    noMeetings: string
    deleteSlotTitle: string
    deleteSlotDescription: string
    deactivateSlotTitle: string
    deactivateSlotDescription: string
    activateSlotTitle: string
    activateSlotDescription: string
    cancelMeetingTitle: string
    cancelMeetingDescription: string
    confirmDeactivate: string
    confirmActivate: string
    confirmCancelMeeting: string
  }
> = {
  ptBr: {
    back: "Admin",
    eyebrow: "Agenda de parcerias",
    titleStart: "Datas e horários",
    titleAccent: "disponíveis",
    description: "Configure os horários que podem ser escolhidos antes de fechar uma parceria. Qualquer horário fora dessa lista é recusado no servidor.",
    released: "Liberados",
    available: "Disponíveis",
    reserved: "Reservados",
    formTitle: "Liberar novo horário",
    formDescription: "Esse horário aparecerá no cadastro somente se estiver ativo e sem reserva.",
    date: "Data",
    time: "Hora",
    duration: "Duração",
    minutes: (count) => `${count} minutos`,
    oneHour: "1 hora",
    oneHourThirty: "1h30",
    internalNote: "Observação interna",
    optional: "Opcional",
    saving: "Salvando...",
    createSlot: "Liberar horário",
    nextSlotsEyebrow: "Próximos horários",
    configuredSchedule: "Agenda configurada",
    reservedStatus: "Reservado",
    availableStatus: "Disponível",
    inactiveStatus: "Inativo",
    fromTo: (start, end) => `${start} até ${end}`,
    activate: "Ativar",
    deactivate: "Desativar",
    delete: "Excluir",
    noFutureSlots: "Nenhum horário futuro cadastrado.",
    requestsEyebrow: "Solicitações",
    scheduledMeetings: "Reuniões agendadas",
    adminShortcutTitle: "Agenda de parcerias",
    adminShortcutSubtitle: (count) => `${count} horários disponíveis`,
    cancelMeeting: "Marcar como cancelada",
    noMeetings: "Nenhuma reunião agendada ainda.",
    deleteSlotTitle: "Excluir horário",
    deleteSlotDescription: "Essa ação remove o horário da agenda e ele não poderá mais ser escolhido no cadastro.",
    deactivateSlotTitle: "Desativar horário",
    deactivateSlotDescription: "Esse horário deixará de aparecer no cadastro, mas continuará salvo no painel.",
    activateSlotTitle: "Ativar horário",
    activateSlotDescription: "Esse horário voltará a aparecer no cadastro se ainda estiver livre.",
    cancelMeetingTitle: "Cancelar reunião",
    cancelMeetingDescription: "Essa ação marca a reunião como cancelada no painel administrativo.",
    confirmDeactivate: "Confirmar desativação",
    confirmActivate: "Confirmar ativação",
    confirmCancelMeeting: "Confirmar cancelamento",
  },
  ptPt: {
    back: "Admin",
    eyebrow: "Agenda de parcerias",
    titleStart: "Datas e horários",
    titleAccent: "disponíveis",
    description: "Configure os horários que podem ser escolhidos antes de fechar uma parceria. Qualquer horário fora desta lista é recusado no servidor.",
    released: "Liberados",
    available: "Disponíveis",
    reserved: "Reservados",
    formTitle: "Liberar novo horário",
    formDescription: "Este horário aparecerá no registo apenas se estiver ativo e sem reserva.",
    date: "Data",
    time: "Hora",
    duration: "Duração",
    minutes: (count) => `${count} minutos`,
    oneHour: "1 hora",
    oneHourThirty: "1h30",
    internalNote: "Observação interna",
    optional: "Opcional",
    saving: "A guardar...",
    createSlot: "Liberar horário",
    nextSlotsEyebrow: "Próximos horários",
    configuredSchedule: "Agenda configurada",
    reservedStatus: "Reservado",
    availableStatus: "Disponível",
    inactiveStatus: "Inativo",
    fromTo: (start, end) => `${start} até ${end}`,
    activate: "Ativar",
    deactivate: "Desativar",
    delete: "Eliminar",
    noFutureSlots: "Nenhum horário futuro registado.",
    requestsEyebrow: "Solicitações",
    scheduledMeetings: "Reuniões agendadas",
    adminShortcutTitle: "Agenda de parcerias",
    adminShortcutSubtitle: (count) => `${count} horários disponíveis`,
    cancelMeeting: "Marcar como cancelada",
    noMeetings: "Nenhuma reunião agendada ainda.",
    deleteSlotTitle: "Eliminar horário",
    deleteSlotDescription: "Esta ação remove o horário da agenda e ele não poderá mais ser escolhido no registo.",
    deactivateSlotTitle: "Desativar horário",
    deactivateSlotDescription: "Este horário deixará de aparecer no registo, mas continuará guardado no painel.",
    activateSlotTitle: "Ativar horário",
    activateSlotDescription: "Este horário voltará a aparecer no registo se ainda estiver livre.",
    cancelMeetingTitle: "Cancelar reunião",
    cancelMeetingDescription: "Esta ação marca a reunião como cancelada no painel administrativo.",
    confirmDeactivate: "Confirmar desativação",
    confirmActivate: "Confirmar ativação",
    confirmCancelMeeting: "Confirmar cancelamento",
  },
  en: {
    back: "Admin",
    eyebrow: "Partnership schedule",
    titleStart: "Available",
    titleAccent: "dates and times",
    description: "Configure the times people can choose before closing a partnership. Any time outside this list is rejected on the server.",
    released: "Released",
    available: "Available",
    reserved: "Reserved",
    formTitle: "Release a new time",
    formDescription: "This time appears in signup only when it is active and unreserved.",
    date: "Date",
    time: "Time",
    duration: "Duration",
    minutes: (count) => `${count} minutes`,
    oneHour: "1 hour",
    oneHourThirty: "1h30",
    internalNote: "Internal note",
    optional: "Optional",
    saving: "Saving...",
    createSlot: "Release time",
    nextSlotsEyebrow: "Upcoming times",
    configuredSchedule: "Configured schedule",
    reservedStatus: "Reserved",
    availableStatus: "Available",
    inactiveStatus: "Inactive",
    fromTo: (start, end) => `${start} to ${end}`,
    activate: "Activate",
    deactivate: "Deactivate",
    delete: "Delete",
    noFutureSlots: "No future times registered.",
    requestsEyebrow: "Requests",
    scheduledMeetings: "Scheduled meetings",
    adminShortcutTitle: "Partnership schedule",
    adminShortcutSubtitle: (count) => `${count} available times`,
    cancelMeeting: "Mark as canceled",
    noMeetings: "No meetings scheduled yet.",
    deleteSlotTitle: "Delete time",
    deleteSlotDescription: "This removes the time from the schedule and it can no longer be chosen during signup.",
    deactivateSlotTitle: "Deactivate time",
    deactivateSlotDescription: "This time will stop appearing during signup, but it remains saved in the admin panel.",
    activateSlotTitle: "Activate time",
    activateSlotDescription: "This time will appear during signup again if it is still free.",
    cancelMeetingTitle: "Cancel meeting",
    cancelMeetingDescription: "This marks the meeting as canceled in the admin panel.",
    confirmDeactivate: "Confirm deactivation",
    confirmActivate: "Confirm activation",
    confirmCancelMeeting: "Confirm cancellation",
  },
  es: {
    back: "Admin",
    eyebrow: "Agenda de alianzas",
    titleStart: "Fechas y horarios",
    titleAccent: "disponibles",
    description: "Configura los horarios que pueden elegirse antes de cerrar una alianza. Cualquier horario fuera de esta lista se rechaza en el servidor.",
    released: "Liberados",
    available: "Disponibles",
    reserved: "Reservados",
    formTitle: "Liberar nuevo horario",
    formDescription: "Este horario aparece en el registro solo si está activo y sin reserva.",
    date: "Fecha",
    time: "Hora",
    duration: "Duración",
    minutes: (count) => `${count} minutos`,
    oneHour: "1 hora",
    oneHourThirty: "1h30",
    internalNote: "Observación interna",
    optional: "Opcional",
    saving: "Guardando...",
    createSlot: "Liberar horario",
    nextSlotsEyebrow: "Próximos horarios",
    configuredSchedule: "Agenda configurada",
    reservedStatus: "Reservado",
    availableStatus: "Disponible",
    inactiveStatus: "Inactivo",
    fromTo: (start, end) => `${start} hasta ${end}`,
    activate: "Activar",
    deactivate: "Desactivar",
    delete: "Eliminar",
    noFutureSlots: "No hay horarios futuros registrados.",
    requestsEyebrow: "Solicitudes",
    scheduledMeetings: "Reuniones agendadas",
    adminShortcutTitle: "Agenda de alianzas",
    adminShortcutSubtitle: (count) => `${count} horarios disponibles`,
    cancelMeeting: "Marcar como cancelada",
    noMeetings: "No hay reuniones agendadas todavía.",
    deleteSlotTitle: "Eliminar horario",
    deleteSlotDescription: "Esta acción elimina el horario de la agenda y ya no podrá elegirse en el registro.",
    deactivateSlotTitle: "Desactivar horario",
    deactivateSlotDescription: "Este horario dejará de aparecer en el registro, pero seguirá guardado en el panel.",
    activateSlotTitle: "Activar horario",
    activateSlotDescription: "Este horario volverá a aparecer en el registro si aún está libre.",
    cancelMeetingTitle: "Cancelar reunión",
    cancelMeetingDescription: "Esta acción marca la reunión como cancelada en el panel administrativo.",
    confirmDeactivate: "Confirmar desactivación",
    confirmActivate: "Confirmar activación",
    confirmCancelMeeting: "Confirmar cancelación",
  },
  fr: {
    back: "Admin",
    eyebrow: "Agenda des partenariats",
    titleStart: "Dates et horaires",
    titleAccent: "disponibles",
    description: "Configurez les horaires qui peuvent être choisis avant de conclure un partenariat. Tout horaire hors de cette liste est refusé par le serveur.",
    released: "Publiés",
    available: "Disponibles",
    reserved: "Réservés",
    formTitle: "Publier un nouvel horaire",
    formDescription: "Cet horaire apparaît dans l'inscription uniquement s'il est actif et non réservé.",
    date: "Date",
    time: "Heure",
    duration: "Durée",
    minutes: (count) => `${count} minutes`,
    oneHour: "1 heure",
    oneHourThirty: "1h30",
    internalNote: "Note interne",
    optional: "Optionnel",
    saving: "Enregistrement...",
    createSlot: "Publier l'horaire",
    nextSlotsEyebrow: "Prochains horaires",
    configuredSchedule: "Agenda configuré",
    reservedStatus: "Réservé",
    availableStatus: "Disponible",
    inactiveStatus: "Inactif",
    fromTo: (start, end) => `${start} à ${end}`,
    activate: "Activer",
    deactivate: "Désactiver",
    delete: "Supprimer",
    noFutureSlots: "Aucun horaire futur enregistré.",
    requestsEyebrow: "Demandes",
    scheduledMeetings: "Réunions planifiées",
    adminShortcutTitle: "Agenda des partenariats",
    adminShortcutSubtitle: (count) => `${count} horaires disponibles`,
    cancelMeeting: "Marquer comme annulée",
    noMeetings: "Aucune réunion planifiée pour le moment.",
    deleteSlotTitle: "Supprimer l'horaire",
    deleteSlotDescription: "Cette action retire l'horaire de l'agenda et il ne pourra plus être choisi lors de l'inscription.",
    deactivateSlotTitle: "Désactiver l'horaire",
    deactivateSlotDescription: "Cet horaire n'apparaîtra plus lors de l'inscription, mais restera enregistré dans le panneau.",
    activateSlotTitle: "Activer l'horaire",
    activateSlotDescription: "Cet horaire réapparaîtra lors de l'inscription s'il est encore libre.",
    cancelMeetingTitle: "Annuler la réunion",
    cancelMeetingDescription: "Cette action marque la réunion comme annulée dans le panneau d'administration.",
    confirmDeactivate: "Confirmer la désactivation",
    confirmActivate: "Confirmer l'activation",
    confirmCancelMeeting: "Confirmer l'annulation",
  },
}

export function statusLabel(status: string, common: CommonCopy) {
  if (status === "PENDING") return common.pendingApproval
  if (status === "APPROVED") return common.approved
  if (status === "REJECTED") return common.rejected
  if (status === "SUSPENDED") return common.suspended
  return status
}

type ContentAssetCopyInput = {
  title: string
  description: string
  type: string
  url: string
}

const defaultContentAssetCopy: Record<
  string,
  Record<ServerLang, { title: string; description: string }>
> = {
  stories: {
    ptBr: {
      title: "Kit de Stories FindB Europa",
      description: "Artes verticais com chamada para cadastro e link exclusivo.",
    },
    ptPt: {
      title: "Kit de Stories FindB Europa",
      description: "Artes verticais com chamada para registo e link exclusivo.",
    },
    en: {
      title: "FindB Europa Stories Kit",
      description: "Vertical creatives with a signup call and exclusive link.",
    },
    es: {
      title: "Kit de Stories FindB Europa",
      description: "Artes verticales con llamada al registro y link exclusivo.",
    },
    fr: {
      title: "Kit de Stories FindB Europa",
      description: "Visuels verticaux avec appel à l'inscription et lien exclusif.",
    },
  },
  script: {
    ptBr: {
      title: "Roteiro para Reels",
      description: "Texto pronto para apresentar a FindB Europa em até 30 segundos.",
    },
    ptPt: {
      title: "Guião para Reels",
      description: "Texto pronto para apresentar a FindB Europa em até 30 segundos.",
    },
    en: {
      title: "Reels Script",
      description: "Ready-to-use text to present FindB Europa in up to 30 seconds.",
    },
    es: {
      title: "Guion para Reels",
      description: "Texto listo para presentar FindB Europa en hasta 30 segundos.",
    },
    fr: {
      title: "Script pour Reels",
      description: "Texte prêt à présenter FindB Europa en 30 secondes maximum.",
    },
  },
  brand: {
    ptBr: {
      title: "Logotipos oficiais",
      description: "Arquivos de marca para publicações aprovadas.",
    },
    ptPt: {
      title: "Logótipos oficiais",
      description: "Ficheiros de marca para publicações aprovadas.",
    },
    en: {
      title: "Official logos",
      description: "Brand files for approved posts.",
    },
    es: {
      title: "Logotipos oficiales",
      description: "Archivos de marca para publicaciones aprobadas.",
    },
    fr: {
      title: "Logos officiels",
      description: "Fichiers de marque pour publications approuvées.",
    },
  },
}

function defaultContentAssetKey(asset: ContentAssetCopyInput) {
  if (asset.url.includes("stories") || asset.type === "STORY") return "stories"
  if (asset.url.includes("roteiro-reels") || asset.type === "SCRIPT") return "script"
  if (asset.url.includes("logos") || asset.type === "BRAND") return "brand"
  return null
}

export function localizeContentAsset<T extends ContentAssetCopyInput>(asset: T, lang: ServerLang) {
  const key = defaultContentAssetKey(asset)
  const translated = key ? defaultContentAssetCopy[key]?.[lang] : null

  if (!translated) {
    return asset
  }

  return {
    ...asset,
    title: translated.title,
    description: translated.description,
  }
}
